version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Build started on `date`
      - mvn -V -U -e package
artifacts:
  files:
    - target/messageUtil-1.0.jar
